package club.heiqi.qz_miner.config;

import club.heiqi.config.schema.ConfigSchema;
import club.heiqi.config.schema.SearchPickerSpec;
import club.heiqi.config.schema.Values;
import club.heiqi.qz_miner.objectgroup.ObjectGroupMode;
import club.heiqi.qz_miner.chain.planner.TunnelDirectionSource;

/**
 * Qz-Miner 配置 Schema（server-safe，零 MC UI / LWJGL 依赖）。
 *
 * <p>默认值统一取自 {@link QzMinerConfigDefaults}。</p>
 */
public final class QzMinerConfigSchema {

    private QzMinerConfigSchema() {
    }

    /**
     * 构建不可变配置 Schema。
     *
     * @return ConfigSchema
     */
    public static ConfigSchema create() {
        return ConfigSchema.builder("qz_miner")
                .title("Qz Miner 配置")
                .section("general")
                    .title("General")
                    .string("greeting").defaultValue(QzMinerConfigDefaults.GREETING)
                        .label("greeting")
                        .helper("How shall I greet?")
                        .build()
                    .number("chainRadius")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CHAIN_RADIUS))
                        .range(1, Integer.MAX_VALUE)
                        .label("chainRadius")
                        .helper("连锁范围半径（方盒子半径，搜索顺序仍为中心扩散）")
                        .build()
                    .number("chainMaxBlocks")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CHAIN_MAX_BLOCKS))
                        .range(1, Integer.MAX_VALUE)
                        .label("chainMaxBlocks")
                        .helper("最大连锁数量；超大值（如 >65536）会显著拖慢规划并加剧 abort 频率，建议根据机器性能调整")
                        .build()
                    .number("chainLoggingShellLayers")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CHAIN_LOGGING_SHELL_LAYERS))
                        .range(1, Integer.MAX_VALUE)
                        .label("chainLoggingShellLayers")
                        .helper("CHAIN 伐木子模式每次向外扩展的壳层数；1 表示围绕当前原木检查一圈 3x3x3 邻域")
                        .build()
                    .number("cableReplaceMaxPerTick")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CABLE_REPLACE_MAX_PER_TICK))
                        .range(1, Integer.MAX_VALUE)
                        .label("cableReplaceMaxPerTick")
                        .helper("GT 线缆连锁替换单 tick 原子上限；超过此值的链路预校验失败不放行（防电压不匹配爆炸）；默认 1024")
                        .build()
                    .number("chainWatchdogTimeoutTicks")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CHAIN_WATCHDOG_TIMEOUT_TICKS))
                        .range(20, Integer.MAX_VALUE)
                        .label("chainWatchdogTimeoutTicks")
                        .helper("连锁看门狗超时阈值（tick）：玩家连锁 N tick 无真实工作推进则协作式回 IDLE（异常兜底，默认 50 ≈ 2.5 秒）")
                        .build()
                    .number("tickBudgetMs")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.TICK_BUDGET_MS))
                        .range(QzMinerConfigDefaults.TICK_BUDGET_MIN_MS, QzMinerConfigDefaults.TICK_BUDGET_MAX_MS)
                        .label("tickBudgetMs")
                        .helper("planning、preview 与普通执行共享的每 Tick soft deadline（毫秒）；默认 15，可配置 1..40")
                        .build()
                    .bool("enableUnlimitedOreFortune")
                        .defaultValue(Boolean.valueOf(QzMinerConfigDefaults.ENABLE_UNLIMITED_ORE_FORTUNE))
                        .label("enableUnlimitedOreFortune")
                        .helper("是否解除 GT/BW/GT++ 普通矿的 3 级时运上限；关闭时保持原版逻辑")
                        .build()
                    .bool("enableFortuneForPlacedOre")
                        .defaultValue(Boolean.valueOf(QzMinerConfigDefaults.ENABLE_FORTUNE_FOR_PLACED_ORE))
                        .label("enableFortuneForPlacedOre")
                        .helper("是否允许非自然生成的 GT/BW 矿石也享受时运；关闭时保持原版仅自然矿可时运")
                        .build()
                    .choice("parallelBudgetMode")
                        .defaultValue(QzMinerConfigDefaults.PARALLEL_BUDGET_MODE)
                        .options(QzMinerConfigDefaults.PARALLEL_BUDGET_MODES.toArray(new String[0]))
                        .label("parallelBudgetMode")
                        .helper("并行执行预算档位：deadline 沿用 tickBudgetMs 共享 deadline（默认，等于现状）；"
                                + "slice 改为每 tick 独立分片预算，主线程不再等满 deadline")
                        .build()
                    .number("parallelSliceBudgetMs")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.PARALLEL_SLICE_BUDGET_MS))
                        .range(1, 40)
                        .label("parallelSliceBudgetMs")
                        .helper("slice 档每 tick 的并行分片预算（毫秒），合法 1..40；deadline 档不生效")
                        .build()
                    .number("harvestExhaustionPerBlock")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.HARVEST_EXHAUSTION_PER_BLOCK))
                        .range(0.0D, QzMinerConfigDefaults.HARVEST_EXHAUSTION_PER_BLOCK_MAX)
                        .label("harvestExhaustionPerBlock")
                        .helper("连锁/爆破每成功破坏一个方块消耗的饥饿值（原版 exhaustion 单位）："
                                + "0.025 等于原版每方块消耗（默认，逐值等于现状），"
                                + "0 表示关闭（0..0.025 无法再降低，等效原版基线）；"
                                + "合法 0..40，40 等于原版 exhaustion 累加上限")
                        .build()
                .endSection()
                .section("client")
                    .title("Client")
                    .bool("clientEnablePreviewRender")
                        .defaultValue(Boolean.valueOf(QzMinerConfigDefaults.CLIENT_ENABLE_PREVIEW_RENDER))
                        .label("clientEnablePreviewRender")
                        .helper("是否启用客户端连锁预览计算与渲染；关闭后将不再执行任何预览相关渲染操作")
                        .build()
                    .choice("tunnelDirectionSource")
                        .defaultValue(QzMinerConfigDefaults.CLIENT_TUNNEL_DIRECTION_SOURCE)
                        .options(TunnelDirectionSource.ids())
                        .label("隧道方向来源")
                        .helper("look_direction 按视线主轴；hit_face 按命中面向方块内部")
                        .build()
                    .bool("autoToolSwapEnabled")
                        .defaultValue(Boolean.valueOf(QzMinerConfigDefaults.CLIENT_AUTO_TOOL_SWAP_ENABLED))
                        .label("autoToolSwapEnabled")
                        .helper("是否启用自动工具换位；关闭时安全还原已有换位")
                        .build()
                    .simpleList("autoToolPrioritySelectors")
                        .defaultValue(java.util.Collections.<String>emptyList())
                        .label("autoToolPrioritySelectors")
                        .helper("有序工具选择器：namespace:path@subtype、namespace:path@* 或 ore:name")
                        .build()
                    .number("clientPreviewMaxRadius")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_MAX_RADIUS))
                        .range(1, Integer.MAX_VALUE)
                        .label("clientPreviewMaxRadius")
                        .helper("客户端最大预览半径；实际预览范围取该值与 chainRadius 的较小值")
                        .build()
                    .number("clientPreviewMaxTargets")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_MAX_TARGETS))
                        .range(1, Integer.MAX_VALUE)
                        .label("clientPreviewMaxTargets")
                        .helper("客户端最大预览目标数量；实际预览数量取该值与服务端 chainMaxBlocks 的较小值")
                        .build()
                    .number("clientPreviewAlphaFadeStartRadius")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_ALPHA_FADE_START_RADIUS))
                        .range(0, Double.MAX_VALUE)
                        .label("clientPreviewAlphaFadeStartRadius")
                        .helper("客户端预览透明度开始衰减的距离半径")
                        .build()
                    .number("clientPreviewAlphaFadeEndRadius")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_ALPHA_FADE_END_RADIUS))
                        .range(0, Double.MAX_VALUE)
                        .label("clientPreviewAlphaFadeEndRadius")
                        .helper("客户端预览透明度衰减到最低值的距离半径")
                        .build()
                    .number("clientPreviewAlphaStartValue")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_ALPHA_START_VALUE))
                        .range(0, 1)
                        .label("clientPreviewAlphaStartValue")
                        .helper("客户端预览透明度的起始值")
                        .build()
                    .number("clientPreviewAlphaEndValue")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_ALPHA_END_VALUE))
                        .range(0, 1)
                        .label("clientPreviewAlphaEndValue")
                        .helper("客户端预览透明度的结束值")
                        .build()
                    .choice("clientPreviewRenderBackend")
                        .defaultValue(QzMinerConfigDefaults.CLIENT_PREVIEW_RENDER_BACKEND)
                        .options(PreviewRenderBackend.ids())
                        .label("clientPreviewRenderBackend")
                        .helper("预览渲染后端：auto 能力探测通过用 shader、否则 legacy（默认）；"
                                + "shader 档探测失败仍回退 legacy 并记录诊断；legacy 恒为固定管线")
                        .build()
                    .number("clientPreviewBarThickness")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_BAR_THICKNESS))
                        .range(0.005, 0.2)
                        .label("clientPreviewBarThickness")
                        .helper("预览条柱粗细（方块坐标偏移缩放），默认 0.045，合法 0.005..0.2")
                        .build()
                    .choice("clientPreviewColorSource")
                        .defaultValue(QzMinerConfigDefaults.CLIENT_PREVIEW_COLOR_SOURCE)
                        .options(PreviewColorSource.ids())
                        .label("clientPreviewColorSource")
                        .helper("预览颜色来源：builtin 内置六色（默认，按大模式区分）；"
                                + "config 使用下方六个 RGB 键的语义配色")
                        .build()
                    .color("clientPreviewColorChain")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_COLOR_CHAIN))
                        .label("clientPreviewColorChain")
                        .helper("CHAIN 大模式（默认子模式）本地预测颜色（0xRRGGBB），默认 0x40E6FF")
                        .build()
                    .color("clientPreviewColorArea")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_COLOR_AREA))
                        .label("clientPreviewColorArea")
                        .helper("AREA 大模式（默认子模式）本地预测颜色（0xRRGGBB），默认 0xE8503C")
                        .build()
                    .color("clientPreviewColorInteract")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_COLOR_INTERACT))
                        .label("clientPreviewColorInteract")
                        .helper("INTERACT 大模式（默认子模式）本地预测颜色（0xRRGGBB），默认 0x58E07A")
                        .build()
                    .color("clientPreviewColorSecondary")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_COLOR_SECONDARY))
                        .label("clientPreviewColorSecondary")
                        .helper("扩展子模式本地预测颜色（0xRRGGBB），默认 0xB08CFF")
                        .build()
                    .color("clientPreviewColorRemote")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_COLOR_REMOTE))
                        .label("clientPreviewColorRemote")
                        .helper("远端预测颜色（0xRRGGBB），默认 0x8FA9D0")
                        .build()
                    .color("clientPreviewColorTruncated")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_COLOR_TRUNCATED))
                        .label("clientPreviewColorTruncated")
                        .helper("截断目标颜色（0xRRGGBB），默认 0xF8C858")
                        .build()
                    .choice("clientPreviewDepthMode")
                        .defaultValue(QzMinerConfigDefaults.CLIENT_PREVIEW_DEPTH_MODE)
                        .options(PreviewDepthMode.ids())
                        .label("clientPreviewDepthMode")
                        .helper("深度通道：xray 恒可见（默认，等于现状）；occlude 参与深度测试；"
                                + "outline 主体遮挡 + 置顶轮廓")
                        .build()
                    .choice("clientPreviewAnimation")
                        .defaultValue(QzMinerConfigDefaults.CLIENT_PREVIEW_ANIMATION)
                        .options(PreviewAnimationMode.ids())
                        .label("clientPreviewAnimation")
                        .helper("预览动画：off 关闭（默认，等于本轮基线）；flow 整体流动；"
                                + "wave 按出现顺序逐波生长（接线属下一批）")
                        .build()
                    .number("clientPreviewAnimationDurationMs")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_ANIMATION_DURATION_MS))
                        .range(0, 2000)
                        .label("clientPreviewAnimationDurationMs")
                        .helper("单代动画时长（毫秒），0 表示瞬时完成，合法 0..2000")
                        .build()
                    .choice("clientPreviewAnimationPhase")
                        .defaultValue(QzMinerConfigDefaults.CLIENT_PREVIEW_ANIMATION_PHASE)
                        .options(PreviewAnimationPhase.ids())
                        .label("clientPreviewAnimationPhase")
                        .helper("动画相位来源：order 用出现序号（默认）；hash 用坐标 + 代次稳定哈希"
                                + "（预留档：本轮未接线，改此键观感不变）")
                        .build()
                    .choice("clientPreviewFadeMode")
                        .defaultValue(QzMinerConfigDefaults.CLIENT_PREVIEW_FADE_MODE)
                        .options(PreviewFadeMode.ids())
                        .label("clientPreviewFadeMode")
                        .helper("距离淡出刷新：timer 1 Hz 兜底（默认，等于现状）；"
                                + "signal 相机变更信号驱动（接线属下一批）；gpu 由着色器逐帧计算")
                        .build()
                    .number("clientPreviewFadeRefreshDistance")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_FADE_REFRESH_DISTANCE))
                        .range(0.0, 8.0)
                        .label("clientPreviewFadeRefreshDistance")
                        .helper("signal 档相机位移阈值（格）：位移达到该值才提升 visual revision，合法 0..8")
                        .build()
                    .number("clientPreviewFadeFallbackMs")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_FADE_FALLBACK_MS))
                        .range(50, 5000)
                        .label("clientPreviewFadeFallbackMs")
                        .helper("signal 档无位移时的兜底刷新间隔（毫秒），合法 50..5000")
                        .build()
                    .number("clientPreviewMinScreenWidthPx")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_MIN_SCREEN_WIDTH_PX))
                        .range(0.0, 8.0)
                        .label("clientPreviewMinScreenWidthPx")
                        .helper("条柱在屏幕上的最小宽度（像素），0 表示不钳制（默认，等于现状）、1..8 生效，"
                                + "合法 0..8；着色器后端按该值单向钳制条柱屏幕宽度")
                        .build()
                    .number("clientPreviewOutlineWidthPx")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_OUTLINE_WIDTH_PX))
                        .range(0.0, 8.0)
                        .label("clientPreviewOutlineWidthPx")
                        .helper("描边壳沿面方向的外扩宽度（物理像素），默认 1.5（等于接线前写死值，观感不变）、"
                                + "0 表示关闭描边，合法 0..8；仅着色器后端的 outline 深度档消费")
                        .build()
                    .bool("clientPreviewFaceShading")
                        .defaultValue(Boolean.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_FACE_SHADING))
                        .label("clientPreviewFaceShading")
                        .helper("是否按面朝向烘焙明暗（顶面最亮、底面最暗），默认 false（等于接线前观感）；"
                                + "开启后 legacy 颜色流与着色器顶点色使用同一张亮度表")
                        .build()
                    .bool("clientPreviewTruncationSignal")
                        .defaultValue(Boolean.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_TRUNCATION_SIGNAL))
                        .label("clientPreviewTruncationSignal")
                        .helper("预览被目标上限截断时是否给出可见提示（默认 false；HUD 文案接线属下一批）")
                        .build()
                    .number("clientPreviewMaxTargetsHardCap")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_MAX_TARGETS_HARD_CAP))
                        .range(1, 4096)
                        .label("clientPreviewMaxTargetsHardCap")
                        .helper("预览目标数量硬顶，合法 1..4096；实际取该值与 clientPreviewMaxTargets、"
                                + "服务端 chainMaxBlocks 的较小值。配额按唯一坐标去重后占用，"
                                + "HUD 的预览已匹配仍是含重复的原始读取数")
                        .build()
                    .choice("clientPreviewLod")
                        .defaultValue(QzMinerConfigDefaults.CLIENT_PREVIEW_LOD)
                        .options(PreviewLodMode.ids())
                        .label("clientPreviewLod")
                        .helper("极端规模 LOD：off 关闭（默认，等于历史行为）；auto 按距离合并并做 alpha 剔除")
                        .build()
                    .number("clientPreviewLodMinAlpha")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_LOD_MIN_ALPHA))
                        .range(0.0, 1.0)
                        .label("clientPreviewLodMinAlpha")
                        .helper("LOD alpha 剔除阈值：低于该值的条柱不参与构建，合法 0..1")
                        .build()
                    .number("clientPreviewOrderMinBrightness")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_ORDER_MIN_BRIGHTNESS))
                        .range(0.0, 1.0)
                        .label("clientPreviewOrderMinBrightness")
                        .helper("连锁序亮度权重下限：预览集合里序号最大（离瞄准起点最远）的条柱乘的亮度权重，"
                                + "合法 0..1；1.0 关闭本能力（等于现状），默认 0.55 时起点 1.0、最远 0.55；"
                                + "只乘颜色亮度，不影响由距离淡出决定的 alpha")
                        .build()
                    .number("clientPreviewInteriorDim")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_INTERIOR_DIM))
                        .range(0.0, 1.0)
                        .label("clientPreviewInteriorDim")
                        .helper("内部结构亮度系数：预览里内部格线（junction 补块 / 共享顶点，无贯通面槽位的顶点）"
                                + "乘的颜色亮度，合法 0..1；1.0 关闭本能力（等于现状），默认 0.65 时内部格线"
                                + "为原亮度的 65%，外轮廓（贯通管面）保持 1.0；只压暗颜色亮度，不影响 alpha，"
                                + "也不作用于描边 pass（描边色即外轮廓）")
                        .build()
                    .bool("clientPreviewSuppressVanillaHighlight")
                        .defaultValue(Boolean.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_SUPPRESS_VANILLA_HIGHLIGHT))
                        .label("clientPreviewSuppressVanillaHighlight")
                        .helper("预览激活且瞄准同一目标时取消原版方块高亮，避免双重指示")
                        .build()
                    .bool("clientPreviewVersionedInputs")
                        .defaultValue(Boolean.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_VERSIONED_INPUTS))
                        .label("clientPreviewVersionedInputs")
                        .helper("是否使用版本化预览输入快照（含目标去抖），默认 false（接线属下一批）；"
                                + "关闭时走逐字段比较")
                        .build()
                    .bool("clientPreviewPresentationOverlay")
                        .defaultValue(Boolean.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_PRESENTATION_OVERLAY))
                        .label("clientPreviewPresentationOverlay")
                        .helper("是否启用统一表现投影覆盖层（HUD 截断 / 进度 / 远端失败的单一事实源）")
                        .build()
                    .bool("clientPreviewExecutionProgress")
                        .defaultValue(Boolean.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_EXECUTION_PROGRESS))
                        .label("clientPreviewExecutionProgress")
                        .helper("是否在 HUD 展示执行进度（已执行 / 匹配）；进度由客户端世界采样得到，默认关闭")
                        .build()
                    .bool("clientPreviewBackendDiagnostics")
                        .defaultValue(Boolean.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_BACKEND_DIAGNOSTICS))
                        .label("clientPreviewBackendDiagnostics")
                        .helper("是否在 HUD 展示预览后端诊断（当前生效后端与一次性回退原因）；默认关闭")
                        .build()
                    .number("clientPreviewRemoteTimeoutMs")
                        .defaultValue(Double.valueOf(QzMinerConfigDefaults.CLIENT_PREVIEW_REMOTE_TIMEOUT_MS))
                        .range(250, 60000)
                        .label("clientPreviewRemoteTimeoutMs")
                        .helper("远端预览请求超时（毫秒），合法 250..60000；超时丢弃陈旧响应并清预览激活")
                        .build()
                    .structuredList("objectGroups", Values.objectWithIdentity(
                            "id",
                            Values.member("id", Values.string()),
                            Values.member("modes", Values.list(Values.choice(ObjectGroupMode.ids())),
                                    java.util.Collections.<String>emptyList()),
                            Values.member("members", Values.widget(Values.list(Values.string()),
                                    Values.searchPicker("qz_miner:block-selector",
                                            SearchPickerSpec.BindingMode.LIST_MEMBERS)))))
                        .defaultValue(QzMinerConfigDefaults.objectGroups())
                        .label("对象组")
                        .helper("按组标识和适用模式组织连锁挖掘对象")
                        .build()
                .endSection()
                .build();
    }
}
